<?php

class Database_MySQLi_Exception extends Database_Driver_Exception {}

class Database_MySQLi_Connect_Exception extends Database_MySQLi_Exception {}

class Database_MySQLi_Query_Exception extends Database_MySQLi_Exception {}

class Database_MySQLi_Select_Query_Exception extends Database_MySQLi_Query_Exception {}

class Database_MySQLi_Select_Invalid_Query_Exception extends Database_MySQLi_Select_Query_Exception {}